#pragma once

typedef struct VERTEX_POSITION{
	FLOAT x;
	FLOAT y;
	FLOAT z;
}VERTEX_POSITION;

typedef struct VERTEX_POSITIONTEX
{
	FLOAT x;
	FLOAT y;
	FLOAT z;
	FLOAT u;
	FLOAT v;
}VERTEX_POSITIONTEX;

typedef enum INPUTELEMENTDESCTYPE
{
	LAYOUTTYPE_POSITION = 0,
	LAYOUTTYPE_POSITIONTEX0,
	LAYOUTTYPE_POSITIONTEX0TEX1,
	LAYOUTTYPE_POSITIONNORMAL,
	LAYOUTTYPE_POSITIONNORMALTEX0,
	LAYOUTTYPE_POSITIONNORMALTEX0TEX1,
}INPUTELEMENTDESCTYPE;

D3D11_INPUT_ELEMENT_DESC* GetLayoutArray(INPUTELEMENTDESCTYPE type); 

UINT GetLayoutArraySize(INPUTELEMENTDESCTYPE type); 
