#pragma once

struct Vertex{
	FLOAT x,y,z;
};

typedef enum INPUTELEMENTDESCTYPE
{
	LAYOUTTYPE_POSITION                = 0,
	LAYOUTTYPE_POSITIONNORMAL          = 1,
	LAYOUTTYPE_POSITIONNORMALTEX0      = 2,
	LAYOUTTYPE_POSITIONNORMALTEX0TEX1  = 3
}INPUTELEMENTDESCTYPE;

D3D11_INPUT_ELEMENT_DESC* GetInputElementDesc(INPUTELEMENTDESCTYPE type); 

UINT GetInputElementDescSize(INPUTELEMENTDESCTYPE type); 

